user:
  name:
    length: 50
  email:
    length: 255
  password:
    length: 6
session:
  remember: 1

per_page: 20

category:
  title:
    length: 255
  rows: 5

comment:
  rows: 3
  minimum: 1
  maximum: 255

user_helper:
  size: 20

book:
  per_page: 8

rate:
  stars: 5
